dist: bionic
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "nightly"
install:
  - pip install -U pipenv
  - pipenv install -d --skip-lock

script: pipenv run pytest --cov=./privex -v -rxXs
after_success:
  - codecov

